name: Build and push the edge image
on:
  release:
    types: [published]

jobs:
    run-pre-checks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - run: |
                  npm ci
                  npm run build
                  npm run formatter
                  npm run tslint
    build-publish-docker-hub:
        needs: run-pre-checks
        runs-on: ubuntu-latest
        steps:
            - uses: azure/docker-login@v1
              with:
                  username: ${{ secrets.REGISTRY_USERNAME }}
                  password: ${{ secrets.REGISTRY_PASSWORD }}
            - uses: actions/checkout@v1
            - name: Build and Push Edge to DockerHub
              shell: bash
              run: ./.github/scripts/build_and_push_release.sh